version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # Managed by NextJS:
      - dependency-name: 'typescript'
      - dependency-name: 'node'
      - dependency-name: 'react'
