export default function Tos() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex"></div>

      <div className="relative flex place-items-start before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1] flex-col gap-4">
        <h1 className="font-mono font-bold text-3xl">Terms of Service & Privacy Policy for Saga</h1>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your use of the Saga mobile application and any related
          services (collectively, the &quot;Service&quot;) provided by Dreifaldt Consulting AB (&quot;we&quot;,
          &quot;us&quot;, or &quot;our&quot;).
        </p>
        <p>
          By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms,
          do not use the Service.
        </p>
        <h2 className="font-mono font-bold text-2xl">Use of the Service </h2>
        Saga provides a platform for generating AI-powered stories (&quot;Content&quot;). You are responsible for your
        use of the Service and any Content you generate or share through the Service.
        <h2 className="font-mono font-bold text-2xl">User-Generated Content</h2> You retain copyright and ownership of
        any Content you create using the Service. You grant us a non-exclusive, worldwide, royalty-free license to use,
        reproduce, distribute, and display the Content within the Service. You are solely responsible for ensuring that
        your Content and your use of the Service comply with all applicable laws and regulations. You agree not to
        generate Content that is unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene, or
        otherwise objectionable or violates any party&apos;s intellectual property.
        <h2 className="font-mono font-bold text-2xl">Changes to the Service</h2> We are a rapidly evolving startup, and
        the Service, including any Content, may change over time. We reserve the right to modify or discontinue,
        temporarily or permanently, the Service (or any part thereof) with or without notice. We are not liable to you
        or any third party for any modification, suspension, or discontinuance of the Service. Disclaimers and
        Limitation of Liability The Service and all Content are provided on an &quot;as is&quot; and &quot;as
        available&quot; basis without any warranties of any kind, either express or implied. We do not guarantee that
        the Service will be secure or available at any particular time or location. We take no responsibility and assume
        no liability for any Content generated by users of the Service. You agree to use the Service at your own risk.
        To the maximum extent permitted by law, we shall not be liable for any direct, indirect, incidental, special,
        consequential, or punitive damages resulting from your access to or use of, or inability to access or use, the
        Service or any Content. <h2 className="font-mono font-bold text-2xl">Termination</h2>
        <p></p>We may terminate or suspend your access to the Service immediately, without prior notice or liability,
        for any reason whatsoever, including without limitation if you breach the Terms.
        <h2 className="font-mono font-bold text-2xl">Changes to Terms</h2>We reserve the right, at our sole discretion,
        to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions
        become effective, you agree to be bound by the revised terms.
        <h2 className="font-mono font-bold text-2xl">Contact Us</h2>
        <p>
          If you have any questions about these Terms, please{' '}
          <a className="text-blue-300 hover:text-blue-700 cursor-pointer" href="mailto:erik@dreifaldt.com">
            contact us
          </a>
          .
        </p>
      </div>

      <div className="mb-32 grid text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-4 lg:text-left" />
    </main>
  )
}
